ScottyLabs/cmu_lost_and_found_v2

- api/package-lock.json
- client/package-lock.json
- client/src/components/FoundItemModal.tsx
- client/src/components/ItemCard.css
- client/src/components/ItemCard.tsx
- client/src/components/SearchBar.css
- client/src/pages/TablePage.css
- client/src/pages/TablePage.tsx
Now the images always show (lazy loaded if possible). Also pinned the search to the top if the user scrolls down on mobile, and displays the report button as a message at the top.
> Simplify cards, display report item message on mobile

- api/enums/locationTypes.ts
- api/index.ts
- api/models/Building.ts
- api/models/Item.ts
- api/routes/buildings.ts
- api/routes/items.ts
- client/src/components/AddItemButton.tsx
- client/src/components/EditItem.tsx
- client/src/components/ItemCard.tsx
- client/src/components/TableWidget.tsx
- client/src/enums/locationTypes.ts
- client/src/interface/building.ts
- client/src/interface/item.ts
- client/src/pages/Admin.tsx
- package-lock.json
- scripts/scraper.py
* Merged buildings and where to retrieve the items. Added a new collection in DB that is auto-populated which contains the retrieve location.
* Disabled delete button when the user has insufficient permissions.
> Short-term fixes

- client/src/components/AddUser.tsx
changed add permission color in add user form
> Add Permission Color Change

- client/src/App.tsx
- client/src/components/ItemCard.css
- client/src/components/ItemCard.tsx
- client/src/pages/Admin.css
- client/src/pages/Policies.tsx
- client/src/pages/TablePage.tsx
easy way to access cmu lost and found page policies 
- possible improvement: pull text directly from cmu lost and found page -jic it gets updated
> add policy page and change image to button

- client/src/components/AddItemButton.tsx
- client/src/pages/Admin.tsx
Resolves #97 by finding location through passing another parameter (permissions) in the AddItemButton function and replacing the value in the form
> Autofill location based on user permission 

- api/controllers/ImageController.ts
- api/routes/auth.ts
Closes #142
Closes #143 
I have no idea how we didn't catch this problem before. (The fix was already merged. I am just cleaning up the Todos here).
> Cleanup debug on auth and image controller

- client/src/components/EditPermissions.tsx
> Added key prop to iterable in EditPermissions

- client/package-lock.json
- client/package.json
- client/src/components/DownloadDataButton/index.tsx
- client/src/components/DownloadDataButton/styles.css
- client/src/pages/Admin.tsx
Adds a download button component that exports the entire admin view to a CSV file.
Closes #94 
- Node.js version: 14
- Desktop/Mobile: Desktop
- OS: macOS Monterey
- Browser: Chromium
> Refactored download button from 24839439a48d8fc2de3fd1e26e22cecc7b383771

- client/src/components/SearchBar.tsx
Replace any with React.ChangeEvent<HTMLInputElement>
Closes #115
> Replace any with React.ChangeEvent<HTMLInputElement>

- client/src/components/AddUser.tsx
Fix missing React key prop in iterator
Closes #137 
- [ x] Bug fix (non-breaking change which fixes an issue)
> Fix missing React key prop in iterator

- client/src/components/HistoryAccordion.tsx
Add missing React key prop
Closes #120
> Add missing React key prop

- client/src/components/ArchiveButton.tsx
- client/src/components/EditItem.tsx
Adds a button that will show up next to the delete item button in the edit item panel. When clicked, this button will archive this single item after a modal prompt.
Closes #160
> Create archive button to archive a single item

- api/models/Item.ts
- api/routes/items.ts
- client/src/interface/item.ts
Closes #165
- Node.js version:
- Python version:
- Desktop/Mobile:
- OS:
- Browser:
> Add dateReturned field

- client/src/components/AddItemButton.css
- client/src/components/AddUser.css
- client/src/components/BulkArchiveButton.tsx
- client/src/components/DownloadDataButton/styles.css
- client/src/components/EditItem.css
- client/src/components/EditItem.tsx
- client/src/components/EditPermissions.tsx
- client/src/components/Header.css
- client/src/components/TableWidget.css
- client/src/components/TableWidget.tsx
- client/src/components/UserTable.css
Some button spacing and alignment was left inconsistent across different screens and devices after a previous change. These new edits now fix these issues.
> Fixed button spacing and alignments

- client/src/components/SearchDropdown.tsx
- client/src/pages/Active.tsx
- client/src/pages/Archived.tsx
This pull request fixes a bug where the search bar only searches by keyword even when other search settings are toggled.
- Node.js version: 14.15.4
- Desktop/Mobile: Desktop
- Browser: Google Chrome
> Fix search dropdown

- api/models/Item.ts
- api/routes/items.ts
Closes #[REPLACE WITH ISSUE NUMBER]
- Node.js version:
- Python version:
- Desktop/Mobile:
- OS:
- Browser:
> Added archive date field

- api/models/Item.ts
- api/routes/items.ts
- client/src/components/HistoryAccordion.tsx
- client/src/components/TableWidget.tsx
- client/src/interface/item.ts
This pull request allows admins to see the email of the person who archived the items. 
Closes #190
I tested this by first creating a new item and archiving the item. Then, I checked if I can see my email on the archiver tab. Next, I unarchived that item and asked someone else to rearchive it. After that, checked if the other person's email is showing up on the archiver tab.
- Node.js version:v18.12.1.
- Python version:3.9.12
- OS: 11.6
- Browser:Chrome
> eblu/<display who archived>

- client/src/pages/Policies.tsx
Update the policy page based on new policy specifications from the UC Info Desk admin.
- Node.js version: 14.18.0
- Desktop/Mobile: Desktop
- Browser: Chrome
> Update policy page

- client/src/components/DownloadDataButton/index.tsx
- client/src/components/SearchBar.tsx
- client/src/components/SearchDropdown.tsx
- client/src/components/TableWidget.tsx
- client/src/components/UserTable.tsx
- client/src/pages/Accounts.tsx
- client/src/pages/Active.tsx
- client/src/pages/Archived.tsx
- client/src/pages/TablePage.tsx
- client/src/utils/itemTableUtils.ts
Major refactors to all pages with tables to support search and sorting while performing mutations and refetches.
Closes #111 
Closes #112 
Closes #113 
Closes #186
> Fix and refactor item and user tables

- client/src/components/DropdownMenu.tsx
- client/src/components/ItemCard.css
Closes #196 
- Node.js version:
- Python version:
- Desktop/Mobile:
- OS:
- Browser:
> Eblu dropdown

- client/src/pages/About.tsx
> Update contributors + add scotty labs

- client/src/components/FoundItemModal.tsx
Updating the text on the home page based on a suggestion from Jesse https://docs.google.com/document/d/1ai38uBJt_keMniLJDKXXc0JibjTTy-cK/edit
> Main page text updates

- client/src/components/AddItemButton.tsx
- client/src/components/EditItem.tsx
- client/src/components/TableWidget.tsx
> edited code for removing image upload

- client/src/components/AddItemButton.tsx
- client/src/components/EditItem.tsx
- client/src/components/ItemCard.tsx
- client/src/components/TableWidget.tsx
> Remove retrieve from locations (only CUC is needed)

- client/src/pages/TablePage.tsx
Changed homepage heading, closes #218
> Update homepage heading

- client/src/components/TableWidget.tsx
> Fix make public perms for building users

- client/src/pages/Policies.tsx
Modified the website policies to match Lost and Found's S25 policies.
> Policy update for S25
